
<h2>Sign up using this form</h2>

<?php echo $this->tag->form("index/register"); ?>

<p>
    <label for="name">Name</label>
    <?php echo $this->tag->textField("name"); ?>
</p>

<p>
    <label for="email">Qty</label>
    <?php echo $this->tag->textField("qty"); ?>
</p>

<p>
    <label for="pswd">Price</label>
    <?php echo $this->tag->textField("price"); ?>
</p>

<p>
    <?php echo $this->tag->submitButton("Register"); ?>
</p>


</form>


